title: Behavior-Driven Development
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Iván Fernández: https://ibanfr.github.io/

plugins:
  - jekyll-linkpreview
  - jekyll-youtube
